
  spring:
    application:
      name: spring-security-jwt
    datasource:
      password: root
      url: jdbc:sqlserver://localhost;databaseName=sample;encrypt=false;
      username: root
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          format_sql: true
      show-sql: true
      defer-datasource-initialization: true
    sql:
      init:
        mode: always
  server:
    port: 8080